### ISSUE TITLE
Steam affecting Preferences for Folders

### ISSUE THREAD

**Issue by mcculleymike** [thargor6/JWildfire#435]
Here is a copy of my JWildfire.cfg from my Steam installation.

[Application]
app.name=JWildfire
app.version=8.10
app.runtime=$ROOTDIR\runtime
app.identifier=org.jwildfire.swing
app.classpath=$ROOTDIR\app\j-wildfire.jar
app.mainjar=$ROOTDIR\app\j-wildfire.jar
app.mainclass=org.jwildfire.swing.JWildfire

[JavaOptions]
-splash:app/splash.png
-Xmx8G

[ArgOptions]

The problem I am having is Steam can't find my base flame files or script files. With the Steam configuration,
I don't know where to point it to by changing preferences. It Used to be in the clean JWildfire you did not have to point
to those folder(s). With this Steam version when I click on the Flame Browser button, it shows that their are no flames available. I click on  "Change folder...." and it opens up my Documents folder, of which there are no Flames! Where is the default folder for flames and scripts in the Steam version of JWF?

**Comment by thargor6** [comment]
This is a misunderstanding. There are no base flame files or base scripts or default folders by design. You point the folder settings in the Preferences to YOUR folders and can then use these folders from different versions of the program. And, most importantly, these folders are never touched when updating the software.

**Comment by mcculleymike** [comment]
Okay, THANKS!

________________________________
